### ISSUE TITLE
🐛 Bug Report: status.whynoipv6.com - IPv4-only

### ISSUE THREAD

**Issue by GoetzGoerisch** [lasseh/whynoipv6#20]
The status page is IPv4-only.

**Comment by lasseh** [comment]
This issue has been reported to them. It is on their roadmap, but there is no ETA yet. https://x.com/zajdee/status/1779228670684479901

I will switch status provider if nothing happens soon.

**Comment by GoetzGoerisch** [comment]
May I ask why this was closed without a resolution?

**Comment by lasseh** [comment]
This has been reported to them, and they have it on the roadmap.
It's not a bug in my code.
I can't find another provider that has the same type of services I use with Betterstack and has IPv6.
